# Generated by Django 5.1.1 on 2024-09-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_postimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='user',
        ),
    ]
